version: "3.3"

services:
  monitor:
    image: network_monitor:1.0.0
    container_name: network_monitor
    ports:
      - "5432:5432/tcp"
      - "5432:5432/udp"
    environment:
      PORTS: "5432"
      LOG_PATH: "/app/logs/data.log"
    restart: always
    network_mode: "bridge"
